### PR TITLE
Security Review

### PR DESCRIPTION
**Pull request by felixrr**
Hi Jeremy,

Like your work on this.  I started using it a little while ago!

Being a professional penetration tester I thought I would give this the once over.  These are my changes.  Most notably there was XSS in the form.  Other than that I have just included hardening features and instructions/healpers for people if they want to enable SSL.

Cheers!

Felix

### CODE REVIEW

**Comment by sciguy14** [comment]
Hey Felix - this looks great. Thanks so much! Sorry I'm just getting around to reviewing it now. I just have a minor request. Some people might not want to use SSL. Though your updates make it optional, it doesn't clearly delineate what steps to do or not do when choosing to use SSL. It would be great if you could do two things:
1. In your updated readme instructions, clearly delineate which steps are optional, and only required for enabling SSL. You should also probably note and warn people that self signed certs will generate a "scary" message about the cert in all modern browsers.
2. Change the default config_sample.php file to not enable SSL by default.

Sound good?

**Comment by felixrr** [comment]
Hi Jeremy,

Sounds sensible enough to me. I have an idea that might make it a little easier for users too but I need to refresh myself on the code first.

Will get back to you!

Felix


On 27 January 2015 17:32:32 GMT+00:00, Jeremy Blum <notifications@github.com> wrote:
>Hey Felix - this looks great. Thanks so much! Sorry I'm just getting
>around to reviewing it now. I just have a minor request. Some people
>might not want to use SSL. Though your updates make it optional, it
>doesn't clearly delineate what steps to do or not do when choosing to
>use SSL. It would be great if you could do two things:
>1. In your updated readme instructions, clearly delineate which steps
>are optional, and only required for enabling SSL. You should also
>probably note and warn people that self signed certs will generate a
>"scary" message about the cert in all modern browsers.
>2. Change the default config_sample.php file to not enable SSL by
>default.
>
>Sound good?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sciguy14/Remote-Wake-Sleep-On-LAN-Server/pull/8#issuecomment-71690160

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by felixrr** [comment]
Hi Jeremy,

I have made some changes.  I was thinking about writing a little install
script but the reality is I won't have the time to do this for a little
while.  So - to get the improvements out to anyone who wants it now, I
figure making those changes you discussed would be a good idea in the
short term.

Felix

**Comment by mew1033** [comment]
I'm interested in seeing this PR merged in. @sciguy14, is there anything else you'd like to see changed before this request can be merged?

**Comment by sciguy14** [comment]
Ooops it completely slipped my mind. I'm moving apartments on Saturday, and will need to set this back up in my new place, so that will be the perfect opportunity for me to test it. I'll test it then, and merge it in if everything looks good. I'm putting it on my calendar so I don't forget! Thanks for the reminder ;)

**Comment by mew1033** [comment]
@sciguy14 Ping. :-)
Hope the move went well!

**Comment by sciguy14** [comment]
Hey sorry - finally testing it.

First, some changes needed to the readme:
1. In the readme, please put a line about what you should fill in when doing the key request. For example, people might think they need to enter a passphrase.
2. Copying `ssl.conf` directly into `mods-enabled` doesn't work. That line needs to change to say that you copy it into `mods-available`. Then run the `a2enmod` command.
3. You need to add another line noting that you need to restart apache: `sudo service apache2 restart` after enabling the headers module
4. When you mention port forwarding, note that port 443 will need to be forwarded if https is enforced. Otherwise, just 80 can be forwarded.

Functionally...
When I have https enabled in the config file, If I navigate to the HTTP URL with a machine name not in the URL, then it redirects to an HTTPS version of the page. However, if I include the machine name in the URL of a HTTP request by appending `?computer=0` the page remains as HTTP instead of HTTPS. that behavior should be made consistent. The else statement on line 29 needs to be updated to match the functionality of the if statement above it.

Furthermore, when I do disable https in the config file, it still redirects to an HTTPS version of the page. This is because you incorrectly have the $USE_HTTPS variable in the config file defined as a string, when it should be a boolean (just remove the quotes). In PHP, a string that is not empty is defined as true, so it was always being set as true, since you had it in quotes.

**Comment by felixrr** [comment]
I think these are now done...

On 07/09/15 19:56, Jeremy Blum wrote:
>
> Hey sorry - finally testing it.
>
> First, some changes needed to the readme:
> 1. In the readme, please put a line about what you should fill in when
> doing the key request. For example, people might think they need to
> enter a passphrase.
> 2. Copying |ssl.conf| directly into |mods-enabled| doesn't work. That
> line needs to change to say that you copy it into |mods-available|.
> Then run the |a2enmod| command.
> 3. You need to add another line noting that you need to restart
> apache: |sudo service apache2 restart| after enabling the headers module
> 4. When you mention port forwarding, note that port 443 will need to
> be forwarded if https is enforced. Otherwise, just 80 can be forwarded.
>
> Functionally...
> When I have https enabled in the config file, If I navigate to the
> HTTP URL with a machine name not in the URL, then it redirects to an
> HTTPS version of the page. However, if I include the machine name in
> the URL of a HTTP request by appending |?computer=0| the page remains
> as HTTP instead of HTTPS. that behavior should be made consistent. The
> else statement on line 29 needs to be updated to match the
> functionality of the if statement above it.
>
> Furthermore, when I do disable https in the config file, it still
> redirects to an HTTPS version of the page. This is because you
> incorrectly have the $USE_HTTPS variable in the config file defined as
> a string, when it should be a boolean (just remove the quotes). In
> PHP, a string that is not empty is defined as true, so it was always
> being set as true, since you had it in quotes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sciguy14/Remote-Wake-Sleep-On-LAN-Server/pull/8#issuecomment-138358368>.
>

-- 

Thanks

Felix

---

To verify my identity please visit:

https://keybase.io/felixrr

**Pull request merged**
